### ISSUE TITLE
android problem

### ISSUE THREAD

**Issue by gustavopradoreis** [ieschalier/expo-sdk-32-demo#1]
Igor, it's working on Android?

I tested your code, and here not worked like in apple.. I see here (https://expo.canny.io/feature-requests/p/android-background-fetch-support) saying it's done..

I tested this way: I loaded on android simulator and also loaded a KML file to simulate a running on city, and i just receive the coords one time or other (in apple works fine).

Did you tested this way? How works for you?

**Comment by ieschalier** [comment]
Hi @gustavopradoreis, I don't test in Android. Do you find a solution ?
